/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RecommendedRouteImport } from './routes/recommended'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayTrackIdRouteImport } from './routes/play.$trackId'
import { Route as ArticlesHowRhythmTypingWorksRouteImport } from './routes/articles.how-rhythm-typing-works'
import { Route as ArticlesChoosingSongsForBetterPracticeRouteImport } from './routes/articles.choosing-songs-for-better-practice'
import { Route as ArticlesBestSongsForTypingSpeedRouteImport } from './routes/articles.best-songs-for-typing-speed'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendedRoute = RecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTrackIdRoute = PlayTrackIdRouteImport.update({
  id: '/play/$trackId',
  path: '/play/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesHowRhythmTypingWorksRoute =
  ArticlesHowRhythmTypingWorksRouteImport.update({
    id: '/how-rhythm-typing-works',
    path: '/how-rhythm-typing-works',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesChoosingSongsForBetterPracticeRoute =
  ArticlesChoosingSongsForBetterPracticeRouteImport.update({
    id: '/choosing-songs-for-better-practice',
    path: '/choosing-songs-for-better-practice',
    getParentRoute: () => ArticlesRoute,
  } as any)
const ArticlesBestSongsForTypingSpeedRoute =
  ArticlesBestSongsForTypingSpeedRouteImport.update({
    id: '/best-songs-for-typing-speed',
    path: '/best-songs-for-typing-speed',
    getParentRoute: () => ArticlesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/guide': typeof GuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommended': typeof RecommendedRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/articles/best-songs-for-typing-speed': typeof ArticlesBestSongsForTypingSpeedRoute
  '/articles/choosing-songs-for-better-practice': typeof ArticlesChoosingSongsForBetterPracticeRoute
  '/articles/how-rhythm-typing-works': typeof ArticlesHowRhythmTypingWorksRoute
  '/play/$trackId': typeof PlayTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/guide': typeof GuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommended': typeof RecommendedRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/articles/best-songs-for-typing-speed': typeof ArticlesBestSongsForTypingSpeedRoute
  '/articles/choosing-songs-for-better-practice': typeof ArticlesChoosingSongsForBetterPracticeRoute
  '/articles/how-rhythm-typing-works': typeof ArticlesHowRhythmTypingWorksRoute
  '/play/$trackId': typeof PlayTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/guide': typeof GuideRoute
  '/how-to-play': typeof HowToPlayRoute
  '/leaderboard': typeof LeaderboardRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommended': typeof RecommendedRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/articles/best-songs-for-typing-speed': typeof ArticlesBestSongsForTypingSpeedRoute
  '/articles/choosing-songs-for-better-practice': typeof ArticlesChoosingSongsForBetterPracticeRoute
  '/articles/how-rhythm-typing-works': typeof ArticlesHowRhythmTypingWorksRoute
  '/play/$trackId': typeof PlayTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/guide'
    | '/how-to-play'
    | '/leaderboard'
    | '/privacy'
    | '/profile'
    | '/recommended'
    | '/support'
    | '/terms'
    | '/articles/best-songs-for-typing-speed'
    | '/articles/choosing-songs-for-better-practice'
    | '/articles/how-rhythm-typing-works'
    | '/play/$trackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/guide'
    | '/how-to-play'
    | '/leaderboard'
    | '/privacy'
    | '/profile'
    | '/recommended'
    | '/support'
    | '/terms'
    | '/articles/best-songs-for-typing-speed'
    | '/articles/choosing-songs-for-better-practice'
    | '/articles/how-rhythm-typing-works'
    | '/play/$trackId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/guide'
    | '/how-to-play'
    | '/leaderboard'
    | '/privacy'
    | '/profile'
    | '/recommended'
    | '/support'
    | '/terms'
    | '/articles/best-songs-for-typing-speed'
    | '/articles/choosing-songs-for-better-practice'
    | '/articles/how-rhythm-typing-works'
    | '/play/$trackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  GuideRoute: typeof GuideRoute
  HowToPlayRoute: typeof HowToPlayRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecommendedRoute: typeof RecommendedRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  PlayTrackIdRoute: typeof PlayTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommended': {
      id: '/recommended'
      path: '/recommended'
      fullPath: '/recommended'
      preLoaderRoute: typeof RecommendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$trackId': {
      id: '/play/$trackId'
      path: '/play/$trackId'
      fullPath: '/play/$trackId'
      preLoaderRoute: typeof PlayTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/how-rhythm-typing-works': {
      id: '/articles/how-rhythm-typing-works'
      path: '/how-rhythm-typing-works'
      fullPath: '/articles/how-rhythm-typing-works'
      preLoaderRoute: typeof ArticlesHowRhythmTypingWorksRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/choosing-songs-for-better-practice': {
      id: '/articles/choosing-songs-for-better-practice'
      path: '/choosing-songs-for-better-practice'
      fullPath: '/articles/choosing-songs-for-better-practice'
      preLoaderRoute: typeof ArticlesChoosingSongsForBetterPracticeRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/articles/best-songs-for-typing-speed': {
      id: '/articles/best-songs-for-typing-speed'
      path: '/best-songs-for-typing-speed'
      fullPath: '/articles/best-songs-for-typing-speed'
      preLoaderRoute: typeof ArticlesBestSongsForTypingSpeedRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesBestSongsForTypingSpeedRoute: typeof ArticlesBestSongsForTypingSpeedRoute
  ArticlesChoosingSongsForBetterPracticeRoute: typeof ArticlesChoosingSongsForBetterPracticeRoute
  ArticlesHowRhythmTypingWorksRoute: typeof ArticlesHowRhythmTypingWorksRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesBestSongsForTypingSpeedRoute: ArticlesBestSongsForTypingSpeedRoute,
  ArticlesChoosingSongsForBetterPracticeRoute:
    ArticlesChoosingSongsForBetterPracticeRoute,
  ArticlesHowRhythmTypingWorksRoute: ArticlesHowRhythmTypingWorksRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  GuideRoute: GuideRoute,
  HowToPlayRoute: HowToPlayRoute,
  LeaderboardRoute: LeaderboardRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecommendedRoute: RecommendedRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  PlayTrackIdRoute: PlayTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
